// ═══════════════════════════════════════════════════════════════
//  xn_interface_layer.h  —  interface-local layer for LAN/USB
//
//  Following "Befehlsbeschreibung XpressNet V3.6 mit LAN/USB
//  Interface 23151, Kommunikation auf den Schnittstellen": a number
//  of messages belong to the INTERFACE itself (the link between the
//  client and this command station), not to the XpressNet bus/
//  command-station logic — and therefore belong here, not in the
//  shared XpressNetHandler (which stays protocol-level, shared by
//  LAN, USB and RS485).
//
//  Intercepted locally (per spec §1 Allgemeines):
//    0xF0        Determine interface version number
//    0xF1/0x01   Interface Status command (also serves as keep-alive)
//    0xF1/0x02   XpressNet Version command
//    0xF1/0x03   Number of free connections (differs per interface!)
//    0xF2/0x01   Determine/change interface device address
//
//  Built on request (the transport layer detects the condition itself):
//    01/01/00    timeout: incomplete frame within ~250ms
//    01/06/07    buffer overflow in the interface
//
//  DELIBERATELY NOT YET IMPLEMENTED (RS485 bus-polling concepts that
//  don't map cleanly onto our LAN/USB architecture, where there is no
//  separate physical bus between "interface" and "command station"):
//    01/02/03, 01/03/02, 01/05/04, 01/07/06, 01/08/09, 01/10/11
//  See project discussion; still to be added once there is a
//  concrete need/interpretation for our architecture.
//
//  All other messages are passed through to the wrapped
//  XpressNetHandler — but any broadcast that is generated
//  synchronously while doing so (e.g. turnout info, loco info) is
//  BUFFERED here instead of being sent immediately. This is because
//  the 01/04/05 acknowledgement ("command has been sent to the
//  command station") is generated by the interface itself,
//  independently of and before any command-station broadcast exists —
//  exactly like the real Lenz interface does (the interface has no
//  knowledge of any resulting broadcast). The caller (LenzLan/LenzUsb)
//  therefore sends its own direct response first (01/04/05, or a
//  REPLY/ERROR), and only afterwards retrieves any buffered broadcast
//  via hasPendingBroadcast()/takePendingBroadcast().
// ═══════════════════════════════════════════════════════════════
#pragma once
#include "xpressnet_handler.h"

// Callback type: returns the number of currently FREE connections/
// sockets for this specific interface (LAN: real W5100/W5500 socket
// status; USB: always a fixed value, since it is a single serial
// link).
using XnFreeConnFn = uint8_t (*)();

class XnInterfaceLayer {
public:
    // process() — main entry point of this layer.
    //
    // Handles one incoming XpressNet frame (without the 0xFF/0xFE|0xFD
    // LAN framing header, exactly as XpressNetHandler::process() also
    // expects it). First checks whether the frame's header/id bytes
    // match one of the interface-local commands listed above (0xF0,
    // 0xF1/0x01, 0xF1/0x02, 0xF1/0x03, 0xF2/0x01); if so, builds and
    // returns the appropriate reply directly, without ever reaching
    // the shared protocol handler. For every other frame, forwards it
    // unchanged to the wrapped handler's own process() function and
    // returns whatever result that produces. See the implementation
    // (xn_interface_layer.cpp) for the exact byte layout of each
    // locally-handled reply.
    //
    // handler:    the wrapped, shared protocol handler for this
    //             specific transport layer (e.g. sXpressNet for LAN,
    //             or sUsbXpressNet for USB).
    // in/il:      the incoming frame bytes and their length.
    // r/l:        output buffer and length for the reply to send back
    //             (filled in by whichever code path handles the frame).
    // freeConnFn: callback answering the "how many free connections do
    //             you have" question, used only for the 0xF1/0x03
    //             command; may be left unset (nullptr), in which case
    //             0xF1/0x03 reports 0 free connections.
    XNHandleResult process(XpressNetHandler& handler,
                            const uint8_t* in, uint8_t il,
                            uint8_t* r, uint8_t& l,
                            XnFreeConnFn freeConnFn);

    // bufferBroadcast() — intended to be called from the wrapped
    // handler's broadcast callback, in place of sending the broadcast
    // immediately. Stores the given bytes internally (see _pending/
    // _pendingLen below) instead of transmitting them straight away —
    // see the class-level comment above for why this ordering matters
    // (the 01/04/05 acknowledgement must reach the client before any
    // resulting broadcast).
    void bufferBroadcast(const uint8_t* data, uint8_t len);

    // hasPendingBroadcast() — returns true if a broadcast produced
    // during the most recent process() call is still waiting to be
    // retrieved and sent by the caller.
    bool    hasPendingBroadcast() const { return _pendingLen > 0; }

    // takePendingBroadcast() — copies the currently buffered
    // broadcast (if any) into the caller-supplied buffer, clears the
    // pending state, and returns the number of bytes copied (0 if
    // there was nothing pending).
    uint8_t takePendingBroadcast(uint8_t* buf);  // copies + clears pending, returns the length

    // Interface-specific error responses — meant to be called by the
    // transport layer itself as soon as IT detects the corresponding
    // condition (only the transport layer knows its own buffer state
    // and timing, e.g. how long a partial frame has been sitting
    // incomplete, or whether its receive buffer is about to overflow).
    // Each of these simply fills the given buffer with the fixed
    // 3-byte error/acknowledgement frame described in the XpressNet
    // interface spec and returns its length (always 3).
    static uint8_t buildFrameTimeoutError(uint8_t* r);    // 01/01/00
    static uint8_t buildBufferOverflowError(uint8_t* r);  // 01/06/07
    static uint8_t buildCommandSentAck(uint8_t* r);       // 01/04/05

private:
    uint8_t _pending[8];
    uint8_t _pendingLen = 0;
};
